apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
# check here (https://kubernetes.io/docs/concepts/storage/storage-classes/)
provisioner: Local
parameters:
  type: ssd
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate