apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: iris
  name: iris-mysql-cronjob
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              imagePullPolicy: IfNotPresent
              image: mysql:5.7
              env:
                - name: MYSQL_BACKUP_USER
                  value: "root"
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: iris-mysql-password
                - name: MYSQL_HOST
                  value: iris-mysql-service
              command:
                - /bin/sh
                - -c
                - |
                  set -ex
                  mysqldump --host=MYSQL_HOST --user=MYSQL_BACKUP_USER \
                            --password=$MYSQL_BACKUP_USER_PASSWORD \
                            --routines --databases appdb --single-transaction \
                            > /mysql-backup/mysql-`date +"%Y%m%d"`.sql
              volumeMounts:
                - mountPath: mysql-backup
                  name: /mysql-backup
          restartPolicy: OnFailure
          volumes:
            - name: mysql-backup
              persistentVolumeClaim:
                claimName: mysql-backup-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backup-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Gi"
