apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iris
  name: iris-mysql-deployment
  labels:
    name: iris-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iris-mysql
  template:
    metadata:
      labels:
        name: iris-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          args:
            - --default_authentication_plugin=mysql_native_password
          ports:
            - containerPort: 3306
              name: mysql-port
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
              subPath: mysql
            - mountPath: /etc/mysql/mysql.conf.d/
              name: mysql-conf
              readOnly: true
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: iris-mysql-password
            - name: HAPROXY_USER
              valueFrom:
                configMapKeyRef:
                  key: haproxy_user
                  name: iris-mysql-config
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: iris-mysql-pvc
        - name: mysql-conf
          configMap:
            name: iris-mysql-config
            items:
              - key: mysqld.cnf
                path: mysqld.cnf