version: "3.8"

services:
  garnet:
    image: ghcr.io/microsoft/garnet:latest
    ulimits:
      memlock: -1
    ports:
      - "16379:6379"
    volumes:
      - garnetdata:/data
volumes:
  garnetdata:
