apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # use minikube standard
  storageClassName: standard
#  mountOptions:
#    - hard
#    - nfsvers=4.1
#  nfs:
#    path: /nfs/grafana     ## NFS 服务器目录
#    server: 192.168.2.31   ## NFS 服务器地址
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: grafana
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: grafana
