version: "3.8"

services:
  nacos:
    image: docker.io/nacos/nacos-server:latest
    container_name: nacos-standalone
    env_file:
      - ./env/nacos.env
    volumes:
      - ./data-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"