version: "3.5"

services:
  kafka-ui:
    image: mirror.gcr.io/provectuslabs/kafka-ui:master
    ports:
      - "8081:8080"
    env_file:
      - kafka.env
    # volumes:
    #   - ./kafka-ui/config.yaml:/etc/kafkaui/dynamic_config.yaml:rw
    networks:
      - zk_kafka
  zookeeper:
    image: mirror.gcr.io/bitnami/zookeeper:3.7.0
    # restart: always
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
    # volumes:
    #   - ./data-zookeeper:/bitnami/zookeeper
    ports:
      - 2181:2181
    networks:
      - zk_kafka
  kafka:
    image: mirror.gcr.io/bitnami/kafka:2.8.0
    # restart: always
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      # - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    # volumes:
    #   - ./data-kafka:/bitnami/kafka
    networks:
      - zk_kafka
networks:
  zk_kafka:
