apiVersion: v1
kind: Service
metadata:
  namespace: iris
  name: iris-mysql-service
  labels:
    name: iris-mysql-service
# this services only inside minikube, there still need a (minikube service) for outside access.
# e.g. minikube service iris-mysql-service -n iris
spec:
  type: NodePort
  selector:
    name: iris-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30016