apiVersion: v1
kind: Pod
metadata:
  name: iris-mysql
  labels:
    name: iris-mysql
spec:
  containers:
    - name: mysql
      image: mysql:8
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: iris-mysql-password
      ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: iris-mysql-volume
  volumes:
    - name: iris-mysql-volume
      emptyDir: { }