apiVersion: v1
kind: Service
metadata:
  namespace: iris
  name: iris-mysql-service
  labels:
    name: iris-mysql-service
spec:
  type: NodePort
  selector:
    name: iris-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30036
#      nodePort: 30016
#      name: iris-mysql-nodeport