name: harus_dev_server

services:
  valkey:
    image: docker.io/bitnami/valkey:8.0
    env_file:
      - prod.env
    volumes:
      - ~/runtime/dev/data/valkey:/bitnami/valkey/data
    ports:
      - "6379:6379"
    networks:
      - harus_network

  kafka:
    image: docker.io/bitnami/kafka:3.8
    env_file:
      - prod.env
    volumes:
      - ~/runtime/dev/data/kafka:/bitnami/kafka
    ports:
      - "9092:9092"
    networks:
      - harus_network

  postgresql:
    image: docker.io/bitnami/postgresql:17.2.0
    env_file:
      - prod.env
    volumes:
      - ~/runtime/dev/data/postgresql:/bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - harus_network

  etcd:
    image: docker.io/bitnami/etcd:3.5
    env_file:
      - prod.env
    volumes:
      - ~/runtime/dev/data/etcd:/bitnami/etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - harus_network

networks:
  harus_network:
    driver: bridge
    external: true
