services:
  valkey:
    image: docker.io/bitnami/valkey:7.2.5
    env_file:
      # - ./github.env
      - ./dev.env
    ports:
      - "6379:6379"
    volumes:
      - dev_valkey_data:/bitnami/valkey/data
  kafka:
    image: docker.io/bitnami/kafka:3.7.0
    env_file:
      # - ./github.env
      - ./dev.env
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - dev_kafka_data:/bitnami/kafka
    ports:
      # - "9093:9093"
      - "9092:9092"
  postgresql:
    image: docker.io/bitnami/postgresql:16.3.0
    env_file:
      # - ./github.env
      - ./dev.env
    ports:
      - "5432:5432"

volumes:
  dev_valkey_data:
  dev_kafka_data:
