version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - flask-redis
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    environment:
      REDIS_HOST: redis
    networks:
      - flask-redis
networks:
  flask-redis:
    driver: bridge