kind: Pod
apiVersion: v1
metadata:
  namespace: iris
  name: nginx
  labels:
    env: test
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
  tolerations:
    - key: example-key
      operator: Exists
      effect: NoSchedule
    - key: must-have-key
      operator: Equal
      value: must-have-value
      effect: NoExecute
      tolerationSeconds: 60