apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pxc
  name: pxc-haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:2.3-alpine
          ports:
            - containerPort: 8888
            - containerPort: 3006
          volumeMounts:
            - mountPath: /usr/local/etc/haproxy
              name: haproxy-config
          command:
            # start haproxy
            - haproxy -f /usr/local/etc/haproxy/haproxy.cfg
      volumes:
        - name: haproxy-config
          configMap:
            items:
              - key: haproxy.cfg
                path: haproxy.cfg
            name: haproxy-config
