version: "3.5"

services:
  prometheus:
    image: bitnami/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus:/opt/bitnami/prometheus/data
      - /az/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      - az-server
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
      # - /az/grafana/log:/var/log/grafana
    networks:
      - az-server
  node_exporter:
    image: bitnami/node-exporter
    container_name: node_exporter
    networks:
      - az-server

networks:
  az-server:
    driver: bridge
    external: true

volumes:
  prometheus:
    name: prometheus
  grafana:
    name: grafana
