version: "3.5"

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    user: root
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    network:
      - iris_network
  kafka1:
    image: "bitnami/kafka:latest"
    user: root
    ports:
      - "9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /iris/elk-stack/kafka1/:/bitnami/kafka
    network:
      - iris_network
  kafka2:
    image: "bitnami/kafka:latest"
    user: root
    ports:
      - "9092"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /iris/elk-stack/kafka2/:/bitnami/kafka
    network:
      - iris_network
  kafka3:
    image: "bitnami/kafka:latest"
    user: root
    ports:
      - "9092"
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /iris/elk-stack/kafka3/:/bitnami/kafka
    network:
      - iris_network
networks:
  iris_network:
    external: true
