apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.azusachino.cn
spec:
  group: azusachino.cn
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    kind: CronTab
    plural: crontabs
    shortNames:
      - ct
    singular: crontab

---
apiVersion: azusachino.cn/v1
kind: CronTab
spec:
  cronSpec: * * * * *
  replicas: 5