apiVersion: v1
kind: ConfigMap
metadata:
  namespace: iris
  name: iris-mysql-config
data:
  haproxy_user: haproxy
  mysqld.cnf: |
    [client]
    default-character-set=utf8
    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    skip_external_locking
    skip-symbolic-links
    memlock=true
    max_connect_errors = 20000
    max_connections = 3000
    skip-name-resolve
    default-time-zone = system
    default-storage-engine = InnoDB
    explicit_defaults_for_timestamp = 1
    lower_case_table_names = 1
    key_buffer_size = 4096M
    table_open_cache = 1024
    sort_buffer_size = 4M
    read_buffer_size = 4M
    thread_cache_size = 128
    query_cache_size = 512M
    character-set-server = utf8
    collation-server = utf8_general_ci
    sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    # innoDB
    innodb_page_size = 16K
    innodb_read_io_threads  = 4
    innodb_write_io_threads = 4
    innodb_io_capacity = 200
    innodb_io_capacity_max = 2000
