apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx-pod
  annotations:
    # 限制出入网带宽
    kubernetes.io/ingress-bandwidth: 1M
    kubernetes.io/egress-bandwidth: 1M
spec:
  preemptionPolicy: PreemptLowerPriority
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: storage
                operator: >
                values:
                  - 50gb
          weight: 100
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/www/html/
          name: nginx-vol
  volumes:
    - name: nginx-vol
      emptyDir: { }