name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    env_file:
      - prod.env
    volumes:
      - /harus/data/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - harus_network

  redis:
    container_name: immich_redis
    image: docker.io/bitnami/valkey:8.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_AOF_ENABLED=yes
    volumes:
      - /harus/data/valkey:/bitnami/valkey/data
    restart: always
    networks:
      - harus_network

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg16-v0.2.1
    env_file:
      - prod.env
    volumes:
      - /harus/data/postgres:/var/lib/postgresql/data
    networks:
      - harus_network

networks:
  harus_network:
    external: true
    driver: bridge
