apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30300
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers: ## 初始化容器，用于修改挂载的存储的文件夹归属组与归属用户
        - name: init-file
          image: busybox:1.34
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command: [ 'chown', '-R', "472:0", "/var/lib/grafana" ]
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
              subPath: grafana
      securityContext:
        fsGroup: 0
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:8.1.2
          securityContext: ## 容器安全策略，设置运行容器使用的归属组与用户
            runAsUser: 472
          ports:
            - name: http
              containerPort: 3000
          env: ## 配置环境变量，设置 Grafana 的默认管理员用户名/密码
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
          readinessProbe: ## 就绪探针
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          livenessProbe: ## 存活探针
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts: ## 容器挂载配置
            - name: data
              mountPath: /var/lib/grafana
              subPath: grafana
      volumes: ## 共享存储挂载配置
        - name: data
          persistentVolumeClaim:
            claimName: grafana
