version: "3.5"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.2
    user: root
    volumes:
      - /iris/elk-stack/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /iris/elk-stack/filebeat/data:/usr/share/filebeat/data

      # 需要抽取的日志内容
      - /iris/elk-stack/filebeat/logs:/var/logs

      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "--strict.perms=false" ]
    networks:
      - iris_network
networks:
  iris_network:
    external: true
