version: "3"
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wiki_for_life
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - wiki_network
  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wiki_for_life
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - wiki_network
networks:
  wiki_network: {}
volumes:
  db-data: