version: "3.8"

services:
  kong-gateway:
    image: docker.io/kong/kong-gateway:3.6-debian
    env_file:
      - prod.env
    networks:
      - kong_network
  postgresql:
    image: docker.io/bitnami/postgresql:17.2.0
    env_file:
      - prod.env
    ports:
      - 15432:5432
    volumes:
      - pg_data:/bitnami/postgresql
    networks:
      - kong_network

volumes:
  pg_data:

networks:
  kong_network: